language: python
python:
  - "2.7"
cache: pip
env:
  matrix:
    - DB=sqlite
    - DB=mysql
    - DB=postgres
    - DB=postgres MC=1
    #- DB=db2
    #- DB=firebird
    #- DB=oracle using snap-ci for oracle
services:
  - memcached

code_climate:
        repo_token: 643c9e479557f45d4eb29e84fce0f0ed845a224f67340a07bc529803ea33e92b

matrix:
  include:
    - python: 2.7
      env:
        - DB=postgres MC=1 SELENIUM=1
      addons:
        sauce_connect: true

# command to install dependencies
install:
  - pip install -r requirements-test.txt
  - pip install -U pytest-sugar pytest-cov coveralls
  - if [ $MC == '1' ]; then pip install -q pylibmc ; fi
  - if [ $SELENIUM == '1' ]; then pip install -q sauceclient ; fi
before_install:
  - chmod +x ci/before_install.sh
  - chmod +x ci/before_install_${DB}.sh
  - chmod +x ci/before_script_${DB}.sh
  - ci/before_install.sh
  - ci/before_install_${DB}.sh
before_script: ci/before_script_${DB}.sh
# command to run tests
script:
 - if [ -z $SELENIUM ]; then py.test -n 2 --cov --cov-report= ; fi
 - if [ $SELENIUM == '1' ]; then py.test --cov --cov-report= ; fi
after_success:
  coveralls

notifications:
  slack: anafteam:ftaeRk3d0Rh0MS5xrAUMasAC
